Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BlogPost.urls')),
    path('users/', include('users.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BlogPost/urls.py
from django.urls import path
from . import views

app_name = 'BlogPost'

urlpatterns = [
    path('', views.BlogList.as_view(), name='index'),

    path('user/<str:username>/', views.UserBlogList.as_view(), name='user_posts'),
    
    path('blog/<int:pk>/', views.BlogDetail.as_view(), name='blog_detail'),
    
    path('new_blog/', views.BlogCreate.as_view(), name='new_blog'),
    
    path('blog/<int:pk>/update/', views.BlogUpdate.as_view(), name='blog_update'),

    path('blog/<int:pk>/delete', views.BlogDelete.as_view(), name='blog_delete'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),

    #path('posts/<int:pk>/', views.user_posts, name='user_posts'),
    #path('posts/<int:pk>/', views.UserBlogList.as_view(), name='user_posts'),
    
    path('profile/', views.profile, name='profile'),

    path('register/', views.register, name='register'),

    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),

    path('password_reset_done/', 
        auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), 
        name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    
    path('password_reset_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), 
        name='password_reset_complete'),
    
] 

users/models.py
from django.db import models
from django.db import models 
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpeg', upload_to='profile_pics')

    def __str__(self):
        return f"{self.user.username} Profile"

    
    

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegistrationForm(UserCreationForm):
    email  = forms.EmailField()
    mobile = forms.IntegerField(min_value=10)

    class Meta:
        model = User
        fields = ['username','email','mobile','password1','password2']


class UserUpdateForm(forms.ModelForm):
    email  = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email']


class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['image']

users/views.py
from BlogPost.models import BlogPost
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import login
from django.contrib import messages
from django.views.generic import ListView
from .forms import UserRegistrationForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.views import (PasswordResetView,
                                       PasswordResetConfirmView)
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def register(request):

    if request.method != 'POST':
        form = UserRegistrationForm()
    else:
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            messages.success(request, 'Your account has been successfully created')
            login(request, new_user)
            return redirect('BlogPost:index')
    
    context = {'form':form}
    return render(request, 'users/register.html', context)


@login_required
def profile(request):
    if request.method != 'POST':
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    else:
        u_form = UserUpdateForm(data=request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Your profile has been successfully updated')
            return redirect('users:profile')
    
    context = {'u_form':u_form, 'p_form':p_form}
    return render(request, 'users/profile.html', context)


class PasswordReset(PasswordResetView):
    email_template_name = 'users/password_reset_email.html'
    template_name = 'users/password_reset.html'
    success_url = reverse_lazy('users:password_reset_done')


class PasswordResetConfirm(PasswordResetConfirmView):
    success_url = reverse_lazy('users:password_reset_complete')
    template_name = 'users/password_reset_confirm.html'


# User posts view using funciton based views
def user_posts(request,pk):
    post_owner = User.objects.get(id=pk)
    user_posts = post_owner.blogpost_set.all().order_by('-date_added')
    paginator = Paginator(user_posts, 3)
    page_number = request.GET.get('page')

    try:
        page_obj = paginator.get_page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.get_page(1)
    except EmptyPage:
        page_obj = paginator.get_page(paginator.num_pages)

    context = {'post_owner':post_owner, 'page_obj':page_obj}
    return render(request, 'users/user_posts.html', context)


# User posts view using class based views
class UserBlogList(ListView):
    model = User
    template_name = 'users/post.html'
    paginate_by = 3
    context_object_name = 'user_posts'
    
    def get_queryset(self):
        owner = get_object_or_404(User, pk=self.kwargs.get('pk'))
        queryset = BlogPost.objects.filter(owner_id=owner.id).order_by('-date_added')
        return queryset

users/templates/users/logged_out.html
{% extends "BlogPost/base.html" %}

{% block content %}

    <p>You have been logged out.</p>

    <div class="border-top pt-3">
        <small class="text-muted">
            <a class="ml-2" href="{% url 'users:login' %}">Log In</a>
        </small>
    </div>

{% endblock content %}

users/templates/users/login.html
{% extends "BlogPost/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Log in to your account.</h2>
{% endblock page_header %}

{% block content %}

    <form method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Log in</button>
            <small class="text-muted">
                <a class="ml-2" href="{% url 'users:password_reset' %}">Forgot Password?</a>
             </small>
        {% endbuttons %}
        
        
    </form>

    <div class="border-top pt-3">
        <small class="text-muted">
           Need an account? <a class="ml-2" href="{% url 'users:register' %}">Register</a>
        </small>
    </div>

{% endblock content %}

users/templates/users/password_reset.html
{% extends "BlogPost/base.html" %}
{% load bootstrap4 %}

{% block content %}
    
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            
            {% buttons %}
                <button name="submit" class="btn btn-primary">Request Password Reset</button>
            {% endbuttons %}
        </form>
        
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "BlogPost/base.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="alert-info">
        Password reset complete.
    </div>
    <a href="{% url 'users:login' %}">Sign In Here</a>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "BlogPost/base.html" %}
{% load bootstrap4 %}

{% block content %}
    
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            
            {% buttons %}
                <button name="submit" class="btn btn-primary">Reset Password</button>
            {% endbuttons %}
        </form>
        
    
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends "BlogPost/base.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="alert-info">
        An email has been sent with instructions to reset your password
    </div>
{% endblock content %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/post.html
{% extends "BlogPost/base.html" %}

{% block page_header %}

  
    {% for post in user_posts|slice:":1" %}
      {% if post.owner == user %}
        <h3>My Blog Posts ({{ page_obj.paginator.count }})</h3>  
       
      {% else %}
        <h3>{{ post.owner }}'s Blog Posts ({{ page_obj.paginator.count }})</h3>  
       
      {% endif %}
    {% endfor %}
 
       
    
    
{% endblock page_header %}


{% block content %}
    
    <ul class="list-group ">
        {% for post in user_posts %}
        <li class="list-group-item">
            <a href="{% url 'BlogPost:blog_detail' post.id %}">
                <b>{{ post }}</b>
            </a>
            
            <a href="{% url 'users:user_posts' post.owner.id %}">
                <small class="ml-2">By {{ post.owner }}</small>
            </a>
            
            <br><br>
            
            <p>{{ post.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ post.text|linebreaks }}</p>

        </li>
        
        {% empty %}
            <p>No blog posts have been added.</p>
        
        {% endfor %}

         
        
    </ul>

    <!-- Pagination-->
        {% if page_obj.has_other_pages %}
            
            <center><p class="pt-4 mb-4">
                {% if page_obj.has_previous %}
                    <a class="btn btn-outline-primary mb-4" href="?page=1">First</a>
                    <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <a class='btn btn-primary mb-4' href="?page={{ num }}">{{ num }}</a>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <a class='btn btn-outline-primary mb-4' href="?page={{ num }}">{{ num }}</a>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                    <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                {% endif %}
            </p></center>

        {% endif %}
{% endblock content %}

users/templates/users/profile.html
{% extends "BlogPost/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    
    <div class="content-section">
        <div class="media">
        <img class="rounded-circle account-img avatar" width="100px" height="100px" src="{{ user.profile.image.url }}">
        <div class="media-body ml-3">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
        </div>
        </div>
    </div>
    
{% endblock page_header %}
    
{% block content %}

        <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group pt-4">
            {% bootstrap_form u_form %}
            {% bootstrap_form p_form %}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-primary" type="submit">Update</button>
        </div>
        </form>

{% endblock content %}

users/templates/users/register.html
{% extends "BlogPost/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Register your account.</h2>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'users:register' %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Register</button>
        {% endbuttons %}
        
        <input type="hidden" name="next" value="{% url 'BlogPost:index' %}">
    </form>
    
    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account? <a class="ml-2" href="#">Log In</a>
        </small>
    </div>

{% endblock content %}

users/templates/users/user_posts.html
{% extends "BlogPost/base.html" %}

{% block page_header %}

    {% if post_owner == user %}
        <h3>My Blog Posts ({{ page_obj.paginator.count }})</h3>  
    
    {% else %}
        <h3>{{ post_owner }}'s Blog Posts ({{ page_obj.paginator.count }})</h3> 
    
    {% endif %}  

{% endblock page_header %}


{% block content %}
    
    <ul class="list-group ">
        
        {% for post in page_obj %}

            <li class="list-group-item">
                <a href="{% url 'BlogPost:blog_detail' post.id %}">
                    <b>{{ post }}</b>
                </a>
                <small class="ml-2">By {{ post_owner }}</small>
                <br><br>
                <p>{{ post.date_added|date:'M d, Y H:i' }}</p>
                <p>{{ post.text|linebreaks }}</p>

                {% if post.owner == user%}
                    <a class='btn btn-outline-primary' href="{% url 'BlogPost:blog_update' post.id %}">Edit</a>
                    <a class='btn btn-outline-danger ml-2' href="{% url 'BlogPost:blog_delete' post.id %}">Delete</a>
                {% endif %}
            </li>
        
        {% empty %}
            <p>No blog posts have been added.</p>
        
        {% endfor %}

        {% if page_obj.has_other_pages %}
            
            <center><p class="pt-4 mb-4">
                {% if page_obj.has_previous %}
                    <a class="btn btn-outline-primary mb-4" href="?page=1">First</a>
                    <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <a class='btn btn-primary mb-4' href="?page={{ num }}">{{ num }}</a>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <a class='btn btn-outline-primary mb-4' href="?page={{ num }}">{{ num }}</a>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                    <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                {% endif %}
            </p></center>

        {% endif %}
    </ul>

{% endblock content %}