Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BlogPost.urls')),
    path('users/', include('users.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BlogPost/urls.py
from django.urls import path
from . import views

app_name = 'BlogPost'

urlpatterns = [
    path('', views.BlogList.as_view(), name='index'),

    path('user/<str:username>/', views.UserBlogList.as_view(), name='user_posts'),
    
    path('blog/<int:pk>/', views.BlogDetail.as_view(), name='blog_detail'),
    
    path('new_blog/', views.BlogCreate.as_view(), name='new_blog'),
    
    path('blog/<int:pk>/update/', views.BlogUpdate.as_view(), name='blog_update'),

    path('blog/<int:pk>/delete', views.BlogDelete.as_view(), name='blog_delete'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),

    #path('posts/<int:pk>/', views.user_posts, name='user_posts'),
    #path('posts/<int:pk>/', views.UserBlogList.as_view(), name='user_posts'),
    
    path('profile/', views.profile, name='profile'),

    path('register/', views.register, name='register'),

    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),

    path('password_reset_done/', 
        auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), 
        name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    
    path('password_reset_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), 
        name='password_reset_complete'),
    
] 

BlogPost/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User 

# Create your models here.
class BlogPost(models.Model):
    """A blog the user is posting."""
    title = models.CharField(max_length=50)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    #def get_absolute_url(self):
    #    return reverse('BlogPost:blog_detail', kwargs={'pk': self.pk})
    

BlogPost/forms.py
from django import forms
from .models import BlogPost

class BlogForm(forms.ModelForm):
    
    class Meta:
        model = BlogPost
        fields = ['title','text']
        labels = {'title':'Title:','text':''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

BlogPost/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from .models import BlogPost
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (ListView, 
                                DetailView, 
                                CreateView, 
                                UpdateView,
                                DeleteView)


class BlogList(ListView):
    model = BlogPost
    template_name = 'BlogPost/index.html'
    context_object_name = 'posts'
    ordering = ['-date_added']
    paginate_by = 5

class UserBlogList(ListView):
    model = BlogPost
    template_name = 'BlogPost/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return BlogPost.objects.filter(owner=user).order_by('-date_added')


class BlogDetail(DetailView):
    model = BlogPost
    template_name = 'BlogPost/blog_detail.html'
    context_object_name = 'post'


class BlogCreate(LoginRequiredMixin, CreateView):
    model = BlogPost
    template_name = 'BlogPost/new_blog.html'
    fields = ['title','text']
    success_url = reverse_lazy('BlogPost:index')
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class BlogUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = BlogPost
    context_object_name = 'post'
    template_name = 'BlogPost/edit_blog.html'
    fields = ['title','text']
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.owner:
            return True
        return False


class BlogDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = BlogPost
    template_name = 'BlogPost/blog_delete.html'
    context_object_name = 'post'  
    success_url = reverse_lazy('BlogPost:index')

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.owner:
            return True
        return False

BlogPost/templates/BlogPost/base.html
{% load static %}
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
    
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
        shrink-to-fit=no">
    <title>BlogPost!</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>

<body>
    
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href = "{% url 'BlogPost:index' %}">
            BlogPost</a>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">

        <ul class="navbar-nav ml-auto">
            
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href = "{% url 'users:profile' %}">{{ user.username }}, Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href = "{% url 'users:logout' %}">Logout</a>
            </li>
            
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href = "{% url 'users:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href = "{% url 'users:register' %}">Register</a>
            </li>
            
            {% endif %}

        </ul>

    </div>

    </nav>

    <main role="main" class="container">
        
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>

        <div>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success">{{ message }}</div>
                {% endfor %}
            {% endif %}

            {% block content %}{% endblock content %}
        </div>

    </main>

</body>

</html>

BlogPost/templates/BlogPost/blog_delete.html
{% extends "BlogPost/base.html" %}

{% block page_header %}
    <h2>Delete blog post:</h2>
{% endblock page_header %}

{% block content %}
    
    <form method='post'>
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ post.title }}"?</p>

        
            <button name="submit" class="btn btn-danger">Yes, delete</button>
            <a class="btn btn-primary" href="{% url 'BlogPost:blog_detail' post.id %}">Cancel</a>
       
        
    </form>

{% endblock content %}

BlogPost/templates/BlogPost/blog_detail.html
{% extends "BlogPost/base.html" %}

{% block page_header %}
{% endblock page_header %}

{% block content %}
    
    <ul class="list-group "> 
        <li class="list-group-item">
            <p><b>{{ post }}</b><small class="ml-2">By {{ post.owner }}</small></p>
            <p>{{ post.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ post.text|linebreaks }}</p>

            {% if post.owner == user%}
                <a class='btn btn-outline-primary' href="{% url 'BlogPost:blog_update' post.id %}">Edit</a>
                <a class='btn btn-outline-danger ml-2' href="{% url 'BlogPost:blog_delete' post.id %}">Delete</a>
            {% endif %}
            
        </li> 
    </ul>

{% endblock content %}

BlogPost/templates/BlogPost/edit_blog.html
{% extends "BlogPost/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Edit blog post:</h2>
{% endblock page_header %}

{% block content %}
    

    <form action="{% url 'BlogPost:blog_update' post.id %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Save changes</button>
        {% endbuttons %}
        
    </form>

{% endblock content %}

BlogPost/templates/BlogPost/index.html
{% extends "BlogPost/base.html" %}

{% block page_header %}

    <div class="jumbotron">

        <h1 class="display-5">Amazing posts all in one place.</h1>

        <p class="lead">Read all you want. Write all you want.
            <br>PS: We take no responsibility for your content.
        </p>
        
        {% if user.is_authenticated %}
        <h4><a href="{% url 'BlogPost:new_blog' %}">Add new blog post</a></h4>

        {% else %}
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
            role="button">Register &raquo;</a>
        
        {% endif %}

    </div>

{% endblock page_header %}

{% block content %}
    
    <ul class="list-group ">
        {% for post in posts %}
        
        <li class="list-group-item">
            <img class="rounded-circle account-img avatar" width="75px" height="75px" src="{{ post.owner.profile.image.url }}">
            <a class="ml-2" href="{% url 'BlogPost:blog_detail' post.id %}">
                <b>{{ post }}<br><a href="{% url 'BlogPost:user_posts' post.owner.username %}">
                    <small class="ml-2">{{ post.owner }}</small>
                </a></b>
            </a>
            
            
            
            <br><br>
            
            <p>{{ post.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ post.text|linebreaks }}</p>

        </li>
        
        {% empty %}
            <p>No blog posts have been added.</p>
        
        {% endfor %}

         
        {% if page_obj.has_other_pages %}
            
            <center><p class="pt-4 mb-4">
                {% if page_obj.has_previous %}
                    <a class="btn btn-outline-primary mb-4" href="?page=1">First</a>
                    <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <a class='btn btn-primary mb-4' href="?page={{ num }}">{{ num }}</a>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <a class='btn btn-outline-primary mb-4' href="?page={{ num }}">{{ num }}</a>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                    <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                {% endif %}
            </p></center>

        {% endif %}  
    </ul>

{% endblock content %}

BlogPost/templates/BlogPost/new_blog.html
{% extends "BlogPost/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Add new blog post:</h2>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'BlogPost:new_blog' %}" method='post' class="forms">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Add blog post</button>
        {% endbuttons %}
    </form>

{% endblock content %}

BlogPost/templates/BlogPost/user_posts.html
{% extends "BlogPost/base.html" %}

{% block page_header %}

    Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})

{% endblock page_header %}

{% block content %}
    
    <ul class="list-group ">
        {% for post in posts %}
        <li class="list-group-item">
            <a href="{% url 'BlogPost:blog_detail' post.id %}">
                <b>{{ post }}</b>
            </a>
            
            
            
            <br><br>
            
            <p>{{ post.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ post.text|linebreaks }}</p>

        </li>
        
        {% empty %}
            <p>No blog posts have been added.</p>
        
        {% endfor %}

         
        {% if page_obj.has_other_pages %}
            
            <center><p class="pt-4 mb-4">
                {% if page_obj.has_previous %}
                    <a class="btn btn-outline-primary mb-4" href="?page=1">First</a>
                    <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <a class='btn btn-primary mb-4' href="?page={{ num }}">{{ num }}</a>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <a class='btn btn-outline-primary mb-4' href="?page={{ num }}">{{ num }}</a>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                    <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                {% endif %}
            </p></center>

        {% endif %}  
    </ul>

{% endblock content %}